// <auto-generated />
#pragma warning disable CS0105
using KoalaLiteDb.Tests.Data;
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System;
using KoalaLiteDb.Tables;

namespace KoalaLiteDb
{
   public sealed class DatabaseBuilder : DatabaseBuilderBase
   {
        public DatabaseBuilder() : this(null) { }
        public DatabaseBuilder(MessagePack.IFormatterResolver resolver) : base(resolver) { }

        public DatabaseBuilder Append(System.Collections.Generic.IEnumerable<Config> dataSource)
        {
            AppendCore(dataSource, x => x.ConfigId, System.StringComparer.Ordinal);
            return this;
        }

    }
}